/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

import static org.junit.jupiter.api.Assertions.assertEquals;

class StringCalculatorTest {
  @Test
  void shouldReturnZeroForEmptyString() {
    assertEquals(0, StringCalculator.add(""));
  }

  @ParameterizedTest
  @CsvSource({"'0', 0", "'1', 1", "'5', 5" })
  void shouldReturnSameNumberForSingleNumberInput(final String input, final int output) {
    assertEquals(output, StringCalculator.add(input));
  }

  @ParameterizedTest
  @CsvSource({"'1,2', 3", "'2,3', 5", "'5,6', 11" })
  void shouldReturnSumForTwoNumbers(final String input, final int output) {
    assertEquals(output, StringCalculator.add(input));
  }

  @Test
  void shouldAddThreeNumbers() {
    assertEquals(6, StringCalculator.add("1,2,3"));
  }

  @Test
  void shouldAddFiveNumbers() {
    assertEquals(15, StringCalculator.add("1,2,3,4,5"));
  }

  @Test
  void shouldAddTenNumbers() {
    assertEquals(55, StringCalculator.add("1,2,3,4,5,6,7,8,9,10"));
  }
}
